# Generated by Django 3.2.13 on 2022-04-16 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('city', models.CharField(max_length=256, verbose_name='city')),
                ('store_type', models.IntegerField(default=1, verbose_name='store_type')),
                ('attachment_id', models.IntegerField(verbose_name='attachment_id')),
                ('stars', models.DecimalField(decimal_places=5, default=0, max_digits=6, verbose_name='stars')),
                ('stars_count', models.IntegerField(default=0, verbose_name='stars_count')),
            ],
            options={
                'db_table': '[db].[COMPANY]',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_parties', models.BooleanField(default=False, verbose_name='has_parties')),
                ('has_deals', models.BooleanField(default=False, verbose_name='has_deals')),
                ('minimum_reservation_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='minimum_reservation_price')),
                ('minimum_reservation_persons', models.IntegerField(verbose_name='minimum_reservation_persons')),
                ('is_open', models.BooleanField(default=False, verbose_name='is_open')),
                ('date', models.DateField(verbose_name='date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve_official.company', verbose_name='company')),
            ],
            options={
                'db_table': '[db].[SCHEDULE]',
            },
        ),
    ]
