# Generated by Django 3.2.13 on 2022-04-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_official', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='COMPANY',
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='SCHEDULE',
        ),
    ]
