# Generated by Django 3.2.13 on 2022-04-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_official', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='store_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='store_id'),
        ),
    ]
