# Generated by Django 3.2.13 on 2022-04-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_official', '0004_alter_notification_store_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
